extends Node

const TICKSPEED = 0.07
const PIPESIZE := Vector2(40, 40)
const WATERSIZE := Vector2(24, 40)

enum SensorType {
	POTENTIOMETER,
	WET_SENSOR,
	JOYSTICK_X,
	JOYSTICK_Y,
	JOYSTICK_Z,
	HALL_EFFECT_SENSOR,
	TOUCH_SENSOR,
	BUTTON,
	STEAM_SENSOR,
	RAGE_SENSOR,
}
